name: Hosting Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/update.yml'

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE22: true

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/gcp-key.json"
          npx firebase-tools deploy --only hosting,firestore:rules --project test-76cdd
          rm gcp-key.json
